version: "3"
services:
  assessment:
    build: .
    container_name: assessment
    restart: always
    ports:
      - "8080:8080"
      - "9095:9095"
    develop:
      watch:
        - action: rebuild
          path: .

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: prometheus
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus

  k6:
    image: grafana/k6:0.51.0
    volumes:
      - "./k6:/scripts"
    environment:
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
      - K6_DURATION=10m
      - K6_VUS=100
      - K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM=true
      - HOST=assessment:8080
    restart: always
    command: ["run", "-o", "experimental-prometheus-rw", "/scripts/loadtest.js"]

  # The Grafana dashboarding server.
  grafana:
    image: grafana/grafana:10.4.3
    volumes:
      - "./grafana/definitions:/var/lib/grafana/dashboards"
      - "./grafana/provisioning:/etc/grafana/provisioning"
    ports:
      - "3000:3000"
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=flameGraph traceqlSearch traceQLStreaming correlations metricsSummary traceqlEditor traceToMetrics traceToProfiles datatrails
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
